### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by askmike** [bitfinexcom/bfx-hf-indicators#50]
I'm maintaining an open source platform to create TA based trading bots called Gekko (MIT license) and I'd like to use this library. However there currently is no license specified. Is it possible to add one?

( EDIT: gekko discussion: https://forum.gekko.wizb.it/thread-57725.html )

**Comment by f3rno** [comment]
@askmike thanks for your interest! Seeing this in Gekko would be very cool. I've added the Apache 2.0 license file: https://github.com/bitfinexcom/bfx-hf-indicators/blob/master/LICENSE

Let me know if you need any other features on the indicator class for the integration

**Comment by xf3rno** [comment]
@robertkowalski this can be closed as well

@askmike let me know if anything came of the integration! I checked earlier this year, didn't notice active usage. I saw you took TALib instead.

As a competitor of sorts to them, let me know if there's anything you find lacking. Iirc performance was an issue when updating large datasets.

**Comment by askmike** [comment]
@xf3rno Gekko actually supported multiple libraries, only got around to implementing both TAlib and Tulip Indicators. Unfortunately before I got around adding this one I have stopped maintaining the open source Gekko project to focus on private prop trading ( :( ).
