### ISSUE TITLE
RSI Calculation

### ISSUE THREAD

**Issue by steoo** [bitfinexcom/bfx-hf-indicators#54]
Hi, I'm trying to understand how to calculate a `RSI[14]`; I don't understand which `value` I should provide to the indicator as I'm retrieving the `Candles` from the websocket and it returns a series of value.
I can help with the documentation when this gets cleared out :)

**Comment by f3rno** [comment]
Hi @steoo, you need to pass any of the candle values (open, high, low, or close) to the RSI `add` method

**Comment by jabarua** [comment]
Hello, Is it posible to use de hf indicators with node, without hf server? tx

**Comment by xf3rno** [comment]
@prdn this can be closed
