### ISSUE TITLE
RSI return value undefined

### ISSUE THREAD

**Issue by AntoLC** [bitfinexcom/bfx-hf-indicators#63]
#### Issue type
- [X ] bug

#### Brief description
I have a problem with the RSI indicator, in some cases it returns "undefined" values. 
I created a simple test based on the example inside the README.md, I get every time "undefined".

#### Steps to reproduce
Inside the directory _test_, create a file _rsi.js_ by example, with the following, then tape "yarn mocha"
```
/* eslint-env mocha */
 'use strict'

 const assert = require('assert')
 const { RSI } = require('../dist')

 describe('RSI', () => {
  it('Test', () => {
    for (let index = 0; index < 100; index++) {
      const rsi = new RSI([8])
      rsi.add(14000)
      rsi.add(14010)
      rsi.add(14025)
      rsi.add(14035)
      rsi.add(14500)
      rsi.add(14100)
      rsi.add(14125)
      rsi.add(14335)
      rsi.add(14600)
      rsi.add(14710)

      console.debug('RSI', rsi.v())

      if (rsi.v().isUndefined()) {
        assert.fail('RSI problem:' + index)
      }
    }

    assert.isOk('RSI OK')
   })
 })
```

- Thank you for your time.

**Comment by robertkowalski** [comment]
thanks for reporting, was able to reproduce the issue. we are going to fix it soon

**Comment by robertkowalski** [comment]
fixed on current master branch :)
